<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>

</body>

<script>

    function descargarClientes() {
        return new Promise((resolve, reject) => {
            const error = false;

            setTimeout(() => {
                if (!error) {
                    resolve('El listado de clientes se descargó correctamente');
                } else {
                    reject('No se pudo descargar la lista de clientes');
                }
            }, 5000);
        });
    }
    function descargarPedidos() {
        return new Promise((resolve, reject) => {
            const error = false;

            setTimeout(() => {
                if (!error) {
                    resolve('El listado de pedidos se descargó correctamente');
                } else {
                    reject('No se pudo descargar la lista de pedidos');
                }
            }, 3000);
        });
    }

    //Por declaración
    async function ejecutar() {
        try {
            const respuesta = await descargarClientes();
            console.log(respuesta);
            const pedidos = await descargarPedidos();
            console.log(pedidos);
        } catch (error) {
            console.error(error);
        }
    }

    /* Para evitar la respuesta secuencial de dos promesas, se utiliza junto con async/Await el Promise.all
    repetir el ejercicio con async/Await y promise.all */

    //Promise.all
    async function ejecutar2() {
        try {
            const [clientes, pedidos] = await Promise.all([descargarClientes(), descargarPedidos()]);
            console.log(clientes);
            console.log(pedidos);
        } catch (error) {
            console.error(error);
        }
    }

    ejecutar2();










</script>

</html>